

export const advertisement = [
    {
        id: 1,
        title: 'Zirconium Crowns',
        description: 'Package',
        image: 'https://www.clicnk.com/assets/images/zirconium-crowns.png',
        firstlink: 'E-Max Laminate veneers or crowns up to 24 teeth',
        secondlink: 'Panoramic x-ray',
        thirdlink: 'Digital smile design',
        fourthlink: 'Non surgical procedure such as tooth extraction, filling, root canal, gingivectomy treatments',
        fifthlink: 'Flight Ticket',
        sixthlink: 'Translation support',
        seventhlink: 'Home medications',
        eighthlink: ' Transportation with private car and translator, 2 ways from and to airport, from hotel to clinic and vice versa',
        ninethlink: ' 5-Star hotel accommodation 7 nights (8 Days) including breakfast with 1 companion',
        tenthlink: 'City tour with private car',
        eleventhlink: 'Follow-up with doctor for 1 year after treatment',
        twelvethlink: '15 years of warranty',
        discount: '30%',
    },
    {
        id: 2,
        title: 'E-Max Laminate Veneers or Crowns',
        description: 'Package',
        image: 'https://www.clicnk.com/assets/images/e-max-laminate-veneers.png',
        firstlink: 'E-Max Laminate veneers or crowns up to 24 teeth',
        secondlink: 'Panoramic x-ray',
        thirdlink: 'Digital smile design',
        fourthlink: 'Non surgical procedure such as tooth extraction, filling, root canal, gingivectomy treatments',
        fifthlink: 'Flight Ticket',
        sixthlink: 'Translation support',
        seventhlink: 'Home medications',
        eighthlink: ' Transportation with private car and translator, 2 ways from and to airport, from hotel to clinic and vice versa',
        ninethlink: ' 5-Star hotel accommodation 7 nights (8 Days) including breakfast with 1 companion',
        tenthlink: 'City tour with private car',
        eleventhlink: 'Follow-up with doctor for 1 year after treatment',
        twelvethlink: '15 years of warranty',
        discount: '35%',
    },
]